name: tapsalon_manager
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.2
  http: ^0.12.0+4
  shared_preferences: ^0.5.6
  intl: ^0.16.0
  google_maps_flutter: ^0.5.26+4
  geolocator: ^5.2.0
  font_awesome_flutter: ^8.5.0
  percent_indicator: ^2.1.1+1
  smooth_star_rating: ^1.0.4+2
  flutter_spinkit: "^4.1.1"
  flutter_widget_from_html_core: ^0.4.2
  share: ^0.6.3+5
  image_picker: ^0.6.7+4
  url_launcher: ^5.4.5
  uploadcare_client: ^2.0.0
  shamsi_date: ^0.8.1
  carousel_slider: ^2.1.0
  photo_view: ^0.10.0
  fluttertoast: ^7.0.2
  najvaflutter: ^1.2.8
  neumorphic: ^0.4.0
  numberpicker: ^1.2.1
  table_calendar: ^2.2.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
#  build_web_compilers: ^2.11.0
  test: ^1.15.2

  flutter_test:
    sdk: flutter
  e2e: ^0.7.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tapsalon_icon_200.png"
flutter:


  uses-material-design: true

  assets:
    - assets/images/tapsalon_icon_200.png
    - assets/images/login_bg.png
    - assets/images/circle.gif
    - assets/images/instagram.png
    - assets/images/telegram.png
    - assets/images/login_header_pic.png

    - assets/images/main_page_salon_ic.png
    - assets/images/user_Icon.png
    - assets/images/marker_ic_1_v1.png
    - assets/images/marker_ic_1_v2.png
    - assets/images/marker_ic_2_v1.png
    - assets/images/marker_ic_2_v2.png
    - assets/images/marker_ic_2_v3.png
    - assets/images/marker_ic_3_v1.png
    - assets/images/marker_ic_3_v2.png
    - assets/images/place_placeholder.jpeg
    - assets/images/gym_placeholder.jpg
    - assets/images/ent_placeholder.jpg
    - assets/images/create_place_header_image.png
    - assets/images/picker_marker_ic.png
    - assets/images/main_page_like_ic.png
    - assets/images/main_page_visit_ic.png
    - assets/images/main_page_comment_ic.png
    - assets/images/main_page_place_ic.png
    - assets/images/man_athelate_ic.png
    - assets/images/woman_athelate_ic.png

  fonts:

    - family: Iransans
      fonts:
        - asset: assets/fonts/IRANSansMobile.ttf
        - asset: assets/fonts/IRANSansMobile_Bold.ttf
        - asset: assets/fonts/IRANSansMobile_Light.ttf
        - asset: assets/fonts/IRANSansMobile_UltraLight.ttf
          weight: 700
    - family: BFarnaz
      fonts:
        - asset: assets/fonts/B_Farnaz.ttf
          weight: 700
